In [1]:
import os
import numpy as np
import statistics
import math

import behavior_analysis_helper_functions_new as helper

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
colors = ["#fd7f6f", "#7eb0d5", "#b2e061", "#bd7ebe", "#ffb55a", "#ffee65", "#beb9db", "#fdcce5", "#8bd3c7"]

In [3]:
# get a list of all folder names in data folder
cohort = 'cohort_2'
cohort_folder = f'/Users/rebekahzhang/Documents/shuler_lab/behavior_data/{cohort}'
data_folder = os.path.join(cohort_folder, 'full_clean_w_all_trials')
print(data_folder)

/Users/rebekahzhang/Documents/shuler_lab/behavior_data/cohort_2/full_clean_w_all_trials

In [4]:
log_1 = os.path.join(data_folder, '509_all_sessions.csv')
training_session_log_1 = pd.read_csv(log_1, index_col=0)
log_2 = os.path.join(data_folder, '510_all_sessions.csv')
training_session_log_2 = pd.read_csv(log_2, index_col=0)
training_session_log = pd.concat([training_session_log_1, training_session_log_2])

In [5]:
training_session_log

,index,date,mouse,dir,filename,training,num_blocks,num_trials,rewards,time,proper_end
0,12,2023-04-25,RZ012,2023-04-25_11-00-06_RZ012,data_RZ012_2023-04-25_11-00-06.txt,regular,3.0,177.0,541.35,1314.41,True
1,34,2023-04-25,RZ013,2023-04-25_11-25-20_RZ013,data_RZ013_2023-04-25_11-25-20.txt,regular,2.0,107.0,367.27,832.84,False
2,75,2023-04-25,RZ014,2023-04-25_11-43-17_RZ014,data_RZ014_2023-04-25_11-43-17.txt,regular,3.0,217.0,458.45,1452.66,True
3,2,2023-04-25,RZ015,2023-04-25_12-10-41_RZ015,data_RZ015_2023-04-25_12-10-41.txt,regular,3.0,185.0,645.04,1517.78,True
4,32,2023-04-25,RZ016,2023-04-25_12-38-31_RZ016,data_RZ016_2023-04-25_12-38-31.txt,regular,3.0,199.0,528.83,1380.37,True
...,...,...,...,...,...,...,...,...,...,...,...
33,13,2023-05-18,RZ012,2023-05-18_10-16-04_RZ012,data_RZ012_2023-05-18_10-16-04.txt,regular,7.0,376.0,929.48,2796.31,True
34,15,2023-05-18,RZ013,2023-05-18_10-18-15_RZ013,data_RZ013_2023-05-18_10-18-15.txt,regular,7.0,340.0,606.73,2111.55,True
35,27,2023-05-18,RZ015,2023-05-18_10-57-02_RZ015,data_RZ015_2023-05-18_10-57-02.txt,regular,7.0,380.0,946.39,2618.22,True
36,3,2023-05-18,RZ016,2023-05-18_14-13-53_RZ016,data_RZ016_2023-05-18_14-13-53.txt,regular,7.0,404.0,548.66,2509.27,True
37,5,2023-05-18,RZ017,2023-05-18_14-15-15_RZ017,data_RZ017_2023-05-18_14-15-15.txt,regular,7.0,382.0,888.42,2670.54,True

In [7]:
mouse_list = training_session_log.mouse.unique().tolist()
mouse_list.sort()
print(mouse_list)

['RZ012', 'RZ013', 'RZ014', 'RZ015', 'RZ016', 'RZ017']